insert into product(name, category, price, manufacturer, unit_in_stock, description) values ("notebook", "machine", 3000, "Samsung", 1000, "최신형노트북")
insert into product(name, category, price, manufacturer, unit_in_stock, description) values ("TV", "machine", 10000, "LG", 100, "화질좋은 tv")
insert into product(name, category, price, manufacturer, unit_in_stock, description) values ("running shoes","shoes", 200,"NiKE", 5000,"뛰어난 쿠션")
insert into product(name, category, price, manufacturer, unit_in_stock, description) values ("닌텐도 스위치", "Game", 360, "닌텐도", 10, "동물의숲")
insert into product(name, category, price, manufacturer, unit_in_stock, description) values ("DVD플레이어", "machine", 100, "LG", 200, "좋은 dvd")
insert into product(name, category, price, manufacturer, unit_in_stock, description) values ("pen", "학용품", 10, "moning gloly", 50000, "좋은펜")
insert into product(name, category, price, manufacturer, unit_in_stock, description) values ("shirt", "dress", 50, "m&m", 2000, "통기성이 좋은 셔츠")
insert into product(name, category, price, manufacturer, unit_in_stock, description) values ("computer", "machine", 550, "Samsung", 500, "싸게팔아요")
insert into product(name, category, price, manufacturer, unit_in_stock, description) values ("note", "학용품", 15, "hansung", 50, "한정 한성노트")
insert into product(name, category, price, manufacturer, unit_in_stock, description) values ("mao", "인형", 20, "happyelement", 20, "귀여운인형")